# Generated by Django 4.2.5 on 2023-09-22 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "listPosition",
                    models.IntegerField(default=1, verbose_name="Позиция в списке"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Вариант ответа"),
                ),
            ],
            options={"ordering": ("listPosition",),},
        ),
        migrations.CreateModel(
            name="RegistrationBallot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "isRegistered",
                    models.BooleanField(
                        default=False,
                        verbose_name="Признак того что пользователь зарегистрирован",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoteBallot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.CharField(
                        max_length=255, verbose_name="Вопрос на голосование"
                    ),
                ),
                (
                    "answers",
                    models.ManyToManyField(
                        blank=True, to="vote.answer", verbose_name="Варианты ответов"
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VotingProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, verbose_name="Дата начала"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, verbose_name="Дата окончания"),
                ),
                (
                    "question",
                    models.CharField(
                        max_length=255, verbose_name="Вопрос на голосование"
                    ),
                ),
                (
                    "answers",
                    models.ManyToManyField(
                        blank=True,
                        to="vote.voteballot",
                        verbose_name="Варианты ответов",
                    ),
                ),
                (
                    "voteBallot",
                    models.ManyToManyField(
                        blank=True, to="vote.answer", verbose_name="Выданные бюллетени"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistrationProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, verbose_name="Дата начала"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, verbose_name="Дата окончания"),
                ),
                (
                    "registrationBallot",
                    models.ManyToManyField(
                        blank=True,
                        to="vote.registrationballot",
                        verbose_name="Выданные бюллетени",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "isRequiredRegistration",
                    models.BooleanField(
                        default=True,
                        verbose_name="Признак необходимости проведения регистрации",
                    ),
                ),
                (
                    "VotingProccess",
                    models.ManyToManyField(
                        blank=True,
                        related_name="meetingVotingProcess",
                        to="vote.registrationprocess",
                        verbose_name="Процессы для проведения голосования по вопросу",
                    ),
                ),
                (
                    "participant",
                    models.ManyToManyField(
                        blank=True,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Перечень пользователей",
                    ),
                ),
                (
                    "registrationProccess",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="meetingRegistrationProcess",
                        to="vote.registrationprocess",
                        verbose_name="Процесс регистрации пользователей",
                    ),
                ),
            ],
        ),
    ]
