# Generated by Django 4.2.5 on 2023-09-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="meeting", name="VotingProccess",),
        migrations.AddField(
            model_name="meeting",
            name="votingProccess",
            field=models.ManyToManyField(
                blank=True,
                related_name="meetingVotingProcess",
                to="vote.votingprocess",
                verbose_name="Процессы для проведения голосования по вопросу",
            ),
        ),
    ]
