# Generated by Django 4.2.5 on 2023-09-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0002_remove_meeting_votingproccess_meeting_votingproccess"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationprocess",
            name="end_date",
            field=models.DateTimeField(blank=True, verbose_name="Дата окончания"),
        ),
        migrations.AlterField(
            model_name="registrationprocess",
            name="start_date",
            field=models.DateTimeField(blank=True, verbose_name="Дата начала"),
        ),
        migrations.AlterField(
            model_name="votingprocess",
            name="end_date",
            field=models.DateTimeField(blank=True, verbose_name="Дата окончания"),
        ),
        migrations.AlterField(
            model_name="votingprocess",
            name="start_date",
            field=models.DateTimeField(blank=True, verbose_name="Дата начала"),
        ),
    ]
