# Generated by Django 4.2.5 on 2023-09-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0003_alter_registrationprocess_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationprocess",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата окончания"
            ),
        ),
    ]
