# Generated by Django 4.2.5 on 2023-09-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0004_alter_registrationprocess_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="votingprocess",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата окончания"
            ),
        ),
    ]
