# Generated by Django 4.2.5 on 2023-09-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0005_alter_votingprocess_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="votingprocess",
            name="answers",
            field=models.ManyToManyField(
                blank=True, to="vote.answer", verbose_name="Варианты ответов"
            ),
        ),
        migrations.AlterField(
            model_name="votingprocess",
            name="voteBallot",
            field=models.ManyToManyField(
                blank=True, to="vote.voteballot", verbose_name="Выданные бюллетени"
            ),
        ),
    ]
