# Generated by Django 4.2.5 on 2023-09-25 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0006_alter_votingprocess_answers_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="votingprocess", name="answers",),
        migrations.AddField(
            model_name="votingprocess",
            name="answers",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="vote.answer",
                verbose_name="Выбранный ответ",
            ),
            preserve_default=False,
        ),
    ]
