# Generated by Django 4.2.5 on 2023-09-25 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0009_rename_answers_votingprocess_answer"),
    ]

    operations = [
        migrations.RemoveField(model_name="voteballot", name="answers",),
        migrations.RemoveField(model_name="voteballot", name="question",),
        migrations.RemoveField(model_name="votingprocess", name="answer",),
        migrations.AddField(
            model_name="voteballot",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="vote.answer",
                verbose_name="Выбранный ответ",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="votingprocess",
            name="answers",
            field=models.ManyToManyField(
                blank=True, to="vote.answer", verbose_name="Варианты ответов"
            ),
        ),
    ]
