# Generated by Django 4.2.5 on 2023-09-25 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0010_remove_voteballot_answers_remove_voteballot_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voteballot",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="vote.answer",
                verbose_name="Выбранный ответ",
            ),
        ),
    ]
