# Generated by Django 4.2.5 on 2023-09-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0011_alter_voteballot_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="votingprocess",
            name="start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата начала"
            ),
        ),
    ]
