# Generated by Django 4.2.5 on 2023-10-03 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0012_alter_votingprocess_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="registrationProcess",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="meetingRegistrationProcess",
                to="vote.registrationprocess",
                verbose_name="Процесс регистрации пользователей",
            ),
        ),
    ]
